### ISSUE TITLE
python get_current_position.py doesnt work

### ISSUE THREAD

**Issue by johnny-wang16** [AGI-Labs/manimo#40]
```
/home/franka/miniconda3/envs/manimo-latest/lib/python3.9/site-packages/glfw/__init__.py:914: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
Failed to import teleop stuff,  No module named 'oculus_reader'
Traceback (most recent call last):
  File "/home/franka/miniconda3/envs/manimo-latest/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/franka/neuralmp_server/manimo/manimo/actuators/arms/franka_arm.py", line 44, in __init__
    self.robot = RobotInterface(
  File "/home/franka/neuralmp_server/manimo/monometis/polymetis/python/polymetis/robot_interface.py", line 348, in __init__
    super().__init__(*args, **kwargs)
  File "/home/franka/neuralmp_server/manimo/monometis/polymetis/python/polymetis/robot_interface.py", line 89, in __init__
    else self.grpc_connection.GetRobotClientMetadata(EMPTY)
  File "/home/franka/miniconda3/envs/manimo-latest/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/franka/miniconda3/envs/manimo-latest/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1731483227.078869494","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3217,"referenced_errors":[{"created":"@1731483227.078868419","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}]}"
>

```
I followed the instruction and finally installed the enviornment on NUC by `source setup_manimo_env_server.sh`. After changing the robot_ip to our IP,  `python get_current_position.py` still does not work. But my original polymetis works. Any suggestions?

**Comment by mohanksriram** [comment]
From your error, I can see that the oculus_reader module is missing. please install it and continue.
`Failed to import teleop stuff,  No module named 'oculus_reader'`

I also recommend you to call `python get_current_position.py` on the client side.
